
[project]
site_name = "Queensland Government Cyber Threat Intelligence"
site_url = "https://intel.cyber.qld.gov.au"
site_description = "Homepage for the Queensland Government Cyber Threat Intelligence"
site_author = "Queensland Government Cyber Threat Intelligence"
repo_url = "https://github.com/qld-gov-au/qgcti-docs"
copyright = "Copyright &copy; 2026 Queensland Government"
extra_css = ["css/stylesheet.css"]
nav = [
    {"Home" = "index.md"},
    {"Terminology and Concepts" = [
        "terminology-and-concepts/index.md",
        "terminology-and-concepts/intelligence-cycle.md",
        "terminology-and-concepts/traffic-light-protocol.md",
        "terminology-and-concepts/permissible-actions-protocol.md",
        "terminology-and-concepts/words-of-estimative-probability.md"
    ]},
    {"Products and Services" = [
        "products-and-services/index.md"
    ]},
    {"Share Intel" = "share-intel/index.md"}
]

[project.theme]
variant = "classic"
features = [
    "navigation.tabs", # Header navigation 
    "navigation.tabs.sticky", # Lock webiste menu
    "navigation.top", # Back to top button
    "navigation.indexes", # Section index page
    "navigation.tracking", # Automatically update with the active anchor highlighted in the table of contents
    "navigation.sections" # Render top-level sections as groups in the sidebar
]
logo = "assets/qldgov-cti.svg"

[project.theme.font]
text = "Noto Sans"

[project.theme.palette]
primary = "custom"
scheme = "default"

[project.extra]
generator = false

[[project.extra.social]]
icon = "fontawesome/regular/envelope"
link = "mailto:intel@cyber.qld.gov.au"

[project.markdown_extensions.abbr]

[project.markdown_extensions.admonition]

[project.markdown_extensions.attr_list]

[project.markdown_extensions.md_in_html]

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.snippets]
auto_append = ["includes/abbreviations.md"]

[project.markdown_extensions.toc]
permalink = true